# -*- coding: utf-8 -*-
"""sistemgaji3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bd8IgNc1snHzJEV9C8Hf67yzJjmWo5nO
"""



# -*- coding: utf-8 -*-
# app.py
import streamlit as st
import json, os
import pandas as pd
from datetime import date, datetime
import altair as alt
from calendar import monthrange

# ---------------------
# Config / DB filename
# ---------------------
DB_FILE = "database.json"

# ---------------------
# Utility: load/save DB
# ---------------------
def load_db():
    if not os.path.exists(DB_FILE):
        return {
            "karyawan": {},  # name -> {password, posisi, absen: { 'YYYY-MM-DD': {status, overtime}}}
            "pemasukan": {},  # 'YYYY-MM' -> int
            "rates": {        # default rates
                "normal": {"intern":35000,"staff":50000,"spv":100000,"manager":200000},
                "overtime": {"intern":20000,"staff":40000,"spv":55000,"manager":65000}
            }
        }
    with open(DB_FILE, "r") as f:
        return json.load(f)

def save_db(db):
    with open(DB_FILE, "w") as f:
        json.dump(db, f, indent=4)

db = load_db()

# ---------------------
# Salary calculation
# ---------------------
def calc_month_salary(name, ym):  # ym = 'YYYY-MM'
    if name not in db["karyawan"]:
        return 0, []
    pos = db["karyawan"][name]["posisi"]
    normal_rate = db["rates"]["normal"].get(pos, 0)
    ot_rate = db["rates"]["overtime"].get(pos, 0)
    total = 0
    rows = []
    absen = db["karyawan"][name].get("absen", {})
    for dstr, info in absen.items():
        if dstr.startswith(ym):
            status = info.get("status","")
            overtime = int(info.get("overtime",0))
            if status == "hadir":
                amt = 8 * normal_rate
                total += amt
                rows.append({"date": dstr, "status": status, "overtime": 0, "amount": amt})
            elif status == "hadir+lembur":
                amt = 8 * normal_rate + overtime * ot_rate
                total += amt
                rows.append({"date": dstr, "status": status, "overtime": overtime, "amount": amt})
            else:
                rows.append({"date": dstr, "status": status, "overtime": 0, "amount": 0})
    return int(total), rows

# ---------------------
# Helper: format Rupiah
# ---------------------
def rp(x):
    try:
        return f"Rp {int(x):,}"
    except:
        return f"Rp {x}"

# ---------------------
# Auth Bendahara
# ---------------------
BEND_EMAIL = "bendahara@email.com"
BEND_PW = "12345"

def bendahara_login_form():
    with st.form("bendahara_login"):
        st.subheader("Login Bendahara")
        email = st.text_input("Email")
        pw = st.text_input("Password", type="password")
        submitted = st.form_submit_button("Login Bendahara")

        if submitted:
            if email.strip().lower() == BEND_EMAIL and pw == BEND_PW:
                st.session_state["bendahara"] = True
                st.success("Login berhasil (bendahara).")
            else:
                st.error("Email atau password bendahara salah.")

# ---------------------
# Auth Karyawan
# ---------------------
def karyawan_register():
    st.subheader("Daftar Karyawan")
    with st.form("reg_form"):
        nama = st.text_input("Nama (unique)").strip().lower()
        pw = st.text_input("Password", type="password")
        posisi = st.selectbox("Posisi", ["intern","staff","spv","manager"])
        submitted = st.form_submit_button("Daftar")

        if submitted:
            if not nama or not pw:
                st.warning("Isi nama dan password.")
            elif nama in db["karyawan"]:
                st.error("Nama sudah terdaftar.")
            else:
                db["karyawan"][nama] = {"password": pw, "posisi": posisi, "absen": {}}
                save_db(db)
                st.success("Pendaftaran berhasil. Silakan login di panel Karyawan.")

def karyawan_login():
    st.subheader("Login Karyawan")
    with st.form("login_form"):
        nama = st.text_input("Nama").strip().lower()
        pw = st.text_input("Password", type="password")
        submitted = st.form_submit_button("Login Karyawan")

        if submitted:
            if nama in db["karyawan"] and db["karyawan"][nama].get("password") == pw:
                st.session_state["karyawan"] = nama
                st.success(f"Login berhasil: {nama.title()}")
            else:
                st.error("Nama atau password salah.")

# ---------------------
# UI
# ---------------------
st.set_page_config(page_title="Sistem Gaji (HR)", layout="wide")
st.title("💼 Sistem Gaji & Absensi — Dashboard")

menu = st.radio("Menu Utama:", ["Beranda","Bendahara","Karyawan","Keluar"], horizontal=True)

st.markdown(f"**Total karyawan:** {len(db['karyawan'])}")
st.markdown("---")

# --------------------- BERANDA ---------------------
if menu == "Beranda":
    st.header("Ringkasan Singkat")
    today = date.today()
    cur_ym = today.strftime("%Y-%m")

    total_payroll = sum(calc_month_salary(name, cur_ym)[0] for name in db["karyawan"].keys())
    total_pemasukan = db.get("pemasukan", {}).get(cur_ym, 0)

    col1, col2, col3 = st.columns(3)
    col1.metric("Jumlah Karyawan", len(db["karyawan"]))
    col2.metric("Total Payroll (Bulan ini)", rp(total_payroll))
    col3.metric("Pemasukan (Bulan ini)", rp(total_pemasukan))

    st.markdown("---")
    st.write("Gunakan menu **Bendahara** untuk analisa & input pemasukan. Gunakan menu **Karyawan** untuk absen & cek gaji.")

# --------------------- BENDARAHA ---------------------
elif menu == "Bendahara":
    if "bendahara" not in st.session_state or not st.session_state["bendahara"]:
        bendahara_login_form()
        st.stop()

    st.success("Akses Bendahara aktif.")
    action = st.selectbox("Pilih Aksi", [
        "Dashboard Evaluasi Bulanan",
        "Input Data Karyawan",
        "Lihat Database",
        "Edit Karyawan",
        "Hapus Karyawan",
        "Input Pemasukan Bulanan",
        "Edit Tarif Gaji per Posisi",
        "Logout Bendahara"
    ])

    # ----------------- Dashboard Evaluasi Bulanan -----------------
    if action == "Dashboard Evaluasi Bulanan":
        st.subheader("📊 Dashboard Evaluasi Bulanan")
        ym = st.date_input("Pilih bulan", value=date.today())
        ym_str = ym.strftime("%Y-%m")
        st.write(f"Menampilkan data untuk: **{ym_str}**")
        rows = []
        for name in db["karyawan"].keys():
            total, _ = calc_month_salary(name, ym_str)
            rows.append({"Nama": name.title(), "Posisi": db["karyawan"][name]["posisi"], "Gaji": total})
        df = pd.DataFrame(rows)
        if not df.empty:
            df["Gaji"] = df["Gaji"].map(lambda x: f"{x:,}")
            st.dataframe(df)
        else:
            st.info("Belum ada data gaji untuk bulan ini.")

    # ----------------- Input Data Karyawan -----------------
    elif action == "Input Data Karyawan":
        st.subheader("➕ Input Data Karyawan")
        with st.form("input_karyawan"):
            nama = st.text_input("Nama (unique)").strip().lower()
            pw = st.text_input("Password (untuk karyawan)", type="password")
            posisi = st.selectbox("Posisi", ["intern","staff","spv","manager"])
            submitted = st.form_submit_button("Simpan")
            if submitted:
                if not nama or not pw:
                    st.warning("Nama & password harus diisi.")
                elif nama in db["karyawan"]:
                    st.error("Nama sudah ada.")
                else:
                    db["karyawan"][nama] = {"password": pw, "posisi": posisi, "absen": {}}
                    save_db(db)
                    st.success("Karyawan tersimpan.")

    # ----------------- Lihat Database -----------------
    elif action == "Lihat Database":
        st.subheader("📋 Lihat Database Karyawan")
        rows = []
        for name, info in db["karyawan"].items():
            rows.append({"Nama": name.title(), "Posisi": info.get("posisi","")})
        df = pd.DataFrame(rows)
        st.dataframe(df)

    # ----------------- Logout Bendahara -----------------
    elif action == "Logout Bendahara":
        st.session_state.pop("bendahara", None)
        st.success("Logout berhasil.")
        st.experimental_rerun()

# --------------------- KARYAWAN ---------------------
elif menu == "Karyawan":
    if "karyawan" not in st.session_state:
        tab1, tab2 = st.tabs(["Login", "Daftar"])
        with tab1:
            karyawan_login()
        with tab2:
            karyawan_register()
        st.stop()

    nama = st.session_state["karyawan"]
    st.success(f"Login sebagai {nama.title()}")

    aksi = st.selectbox("Pilih Aksi", ["Absen Hari Ini", "Lihat Gaji Bulanan", "Riwayat Absensi", "Logout"])

    # Absen Hari Ini
    if aksi == "Absen Hari Ini":
        st.subheader("📅 Absen Hari Ini")
        today = date.today().strftime("%Y-%m-%d")
        status = st.selectbox("Status", ["hadir", "hadir+lembur", "izin", "sakit", "cuti"])
        overtime = 0
        if status == "hadir+lembur":
            overtime = st.number_input("Jumlah jam lembur", min_value=1, max_value=12)
        if st.button("Simpan Absen"):
            if "absen" not in db["karyawan"][nama]:
                db["karyawan"][nama]["absen"] = {}
            db["karyawan"][nama]["absen"][today] = {"status": status, "overtime": overtime}
            save_db(db)
            st.success("Absensi tersimpan.")

    # Lihat Gaji Bulanan
    elif aksi == "Lihat Gaji Bulanan":
        st.subheader("💵 Gaji Bulanan")
        bulan = st.date_input("Pilih bulan", value=date.today())
        ym_str = bulan.strftime("%Y-%m")
        total, rows = calc_month_salary(nama, ym_str)
        st.write(f"Total gaji bulan **{ym_str}**: {rp(total)}")
        if rows:
            df = pd.DataFrame(rows)
            df["amount"] = df["amount"].map(lambda x: f"{x:,}")
            st.dataframe(df)
        else:
            st.info("Tidak ada data absensi bulan ini.")

    # Riwayat Absensi
    elif aksi == "Riwayat Absensi":
        st.subheader("📂 Riwayat Absensi")
        absen = db["karyawan"][nama].get("absen", {})
        if not absen:
            st.info("Belum ada data absensi.")
        else:
            rows = [{"Tanggal": d, "Status": v["status"], "Lembur": v.get("overtime",0)} for d,v in absen.items()]
            df = pd.DataFrame(rows).sort_values("Tanggal")
            st.dataframe(df)

    # Logout
    elif aksi == "Logout":
        st.session_state.pop("karyawan", None)
        st.success("Logout berhasil.")
        st.experimental_rerun()

# --------------------- Keluar ---------------------
elif menu == "Keluar":
    st.write("Terima kasih telah menggunakan sistem.")
