# -*- coding: utf-8 -*-
"""sistemgaji3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bd8IgNc1snHzJEV9C8Hf67yzJjmWo5nO
"""



# app.py
import streamlit as st
import json, os
import pandas as pd
from datetime import date, datetime
import altair as alt
from calendar import monthrange

# ---------------------
# Config / DB filename
# ---------------------
DB_FILE = "databaseghe3.json"

# ---------------------
# Utility: load/save DB
# ---------------------
def load_db():
    if not os.path.exists(DB_FILE):
        # default structure
        return {
            "karyawan": {},    # name -> {password, posisi, weeks? (optional), absen: { 'YYYY-MM-DD': {status, overtime}}}
            "pemasukan": {},   # 'YYYY-MM' -> int
            "rates": {         # default rates
                "normal": {"intern":35000,"staff":50000,"spv":100000,"manager":200000},
                "overtime": {"intern":20000,"staff":40000,"spv":55000,"manager":65000}
            }
        }
    with open(DB_FILE, "r") as f:
        return json.load(f)

def save_db(db):
    with open(DB_FILE, "w") as f:
        json.dump(db, f, indent=4)

db = load_db()

# ---------------------
# Salary calculation
# ---------------------
def calc_month_salary(name, ym):  # ym = 'YYYY-MM'
    """
    iterate attendance entries for that month and compute:
    hadir = 8h * normal_rate
    hadir+lembur = 8h*normal + overtime_hours*overtime_rate
    izin/sakit/cuti = 0
    return total_amount, detail_rows(list of tuples)
    """
    if name not in db["karyawan"]:
        return 0, []
    pos = db["karyawan"][name]["posisi"]
    normal_rate = db["rates"]["normal"].get(pos, 0)
    ot_rate = db["rates"]["overtime"].get(pos, 0)
    total = 0
    rows = []
    # iterate absen keys
    absen = db["karyawan"][name].get("absen", {})
    for dstr, info in absen.items():
        if dstr.startswith(ym):
            status = info.get("status","")
            overtime = int(info.get("overtime",0))
            if status == "hadir":
                amt = 8 * normal_rate
                total += amt
                rows.append({"date": dstr, "status": status, "overtime": 0, "amount": amt})
            elif status == "hadir+lembur":
                amt = 8 * normal_rate + overtime * ot_rate
                total += amt
                rows.append({"date": dstr, "status": status, "overtime": overtime, "amount": amt})
            else: # izin/sakit/cuti
                rows.append({"date": dstr, "status": status, "overtime": 0, "amount": 0})
    return int(total), rows

# ---------------------
# Helper: format Rupiah
# ---------------------
def rp(x):
    try:
        return f"Rp {int(x):,}"
    except:
        return f"Rp {x}"

# ---------------------
# Auth (karyawan & bendahara)
# ---------------------
BEND_EMAIL = "bendahara@email.com"
BEND_PW = "12345"

def bendahara_login_form():
    st.subheader("Login Bendahara")
    email = st.text_input("Email", key="bend_email")
    pw = st.text_input("Password", type="password", key="bend_pw")
    if st.button("Login Bendahara"):
        if email.strip().lower() == BEND_EMAIL and pw == BEND_PW:
            st.session_state["bendahara"] = True
            st.success("Login berhasil (bendahara).")
            st.experimental_rerun()
        else:
            st.error("Email atau password bendahara salah.")

def karyawan_register():
    st.subheader("Daftar Karyawan")
    col1, col2 = st.columns(2)
    with col1:
        nama = st.text_input("Nama (unique)", key="reg_nama")
    with col2:
        pw = st.text_input("Password", type="password", key="reg_pw")
    posisi = st.selectbox("Posisi", ["intern","staff","spv","manager"], key="reg_pos")
    if st.button("Daftar"):
        if not nama or not pw:
            st.warning("Isi nama dan password.")
        else:
            key = nama.strip().lower()
            if key in db["karyawan"]:
                st.error("Nama sudah terdaftar, gunakan nama lain atau login.")
            else:
                db["karyawan"][key] = {"password": pw, "posisi": posisi, "absen": {}}
                save_db(db)
                st.success("Pendaftaran berhasil. Silakan login di panel Karyawan.")

def karyawan_login():
    st.subheader("Login Karyawan")
    nama = st.text_input("Nama", key="login_nama")
    pw = st.text_input("Password", type="password", key="login_pw")
    if st.button("Login Karyawan"):
        key = nama.strip().lower()
        if key in db["karyawan"] and db["karyawan"][key].get("password") == pw:
            st.session_state["karyawan"] = key
            st.success(f"Login berhasil: {key.title()}")
            st.experimental_rerun()
        else:
            st.error("Nama atau password salah.")

# ---------------------
# UI: Top navigation
# ---------------------
st.set_page_config(page_title="Sistem Gaji (HR)", layout="wide")
st.title("💼 Sistem Gaji & Absensi — Dashboard")

# Top menu
menu = st.radio("Menu Utama:", ["Beranda","Bendahara","Karyawan","Keluar"], horizontal=True)

# Quick info (bisa tetap di sidebar atau di atas)
st.markdown(f"**Total karyawan:** {len(db['karyawan'])}")
st.markdown("---")


# ---------------------
# BERANDA
# ---------------------
if menu == "Beranda":
    st.header("Ringkasan Singkat")
    total_k = len(db["karyawan"])

    # bulan & tahun saat ini
    today = date.today()
    cur_ym = today.strftime("%Y-%m")

    # total payroll bulan ini
    total_payroll = sum(calc_month_salary(name, cur_ym)[0] for name in db["karyawan"].keys())

    # pemasukan bulan ini
    total_pemasukan = db.get("pemasukan", {}).get(cur_ym, 0)

    # tampilkan ringkasan
    col1, col2, col3 = st.columns(3)
    col1.metric("Jumlah Karyawan", total_k)
    col2.metric("Total Payroll (Bulan ini)", rp(total_payroll))
    col3.metric("Pemasukan (Bulan ini)", rp(total_pemasukan))

    st.markdown("---")
    st.write("Gunakan menu **Bendahara** untuk analisa & input pemasukan. Gunakan menu **Karyawan** untuk absen & cek gaji.")


# ---------------------
# BENDARAHA
# ---------------------
elif menu == "Bendahara":
    st.header("🔐 Bendahara — Admin Panel")
    if "bendahara" not in st.session_state or not st.session_state["bendahara"]:
        bendahara_login_form()
        st.stop()

    # authenticated
    st.success("Akses Bendahara aktif.")
    action = st.selectbox("Pilih Aksi", [
        "Dashboard Evaluasi Bulanan",
        "Input Data Karyawan",
        "Lihat Database",
        "Edit Karyawan",
        "Hapus Karyawan",
        "Input Pemasukan Bulanan",
        "Edit Tarif Gaji per Posisi",
        "Logout Bendahara"
    ])

    # ----------------- Dashboard Evaluasi Bulanan -----------------
    if action == "Dashboard Evaluasi Bulanan":
        st.subheader("📊 Dashboard Evaluasi Bulanan")
        # choose month-year
        ym = st.date_input("Pilih bulan (pilih tanggal dalam bulan yang diinginkan):", value=date.today())
        ym_str = ym.strftime("%Y-%m")
        st.write(f"Menampilkan data untuk: **{ym_str}**")
        # total pengeluaran gaji per bulan: sum of calc_month_salary
        rows = []
        for name in db["karyawan"].keys():
            total, details = calc_month_salary(name, ym_str)
            rows.append({"nama": name.title(), "posisi": db["karyawan"][name]["posisi"], "gaji": total})
        df = pd.DataFrame(rows)
        if df.empty:
            st.info("Belum ada data gaji untuk bulan ini.")
        else:
            df = df.sort_values("gaji", ascending=False)
            df["gaji_fmt"] = df["gaji"].map(lambda x: f"{int(x):,}")
            st.markdown("**Tabel Gaji Karyawan (bulan)**")
            st.dataframe(df[["nama","posisi","gaji_fmt"]].rename(columns={"nama":"Nama","posisi":"Posisi","gaji_fmt":"Gaji (Rp)"}), use_container_width=True)

            total_pengeluaran = int(df["gaji"].sum())
            st.metric("Total Pengeluaran Gaji (bulan)", rp(total_pengeluaran))
            # pemasukan bulan
            pemasukan_val = db.get("pemasukan", {}).get(ym_str, 0)
            st.metric("Pemasukan (bulan)", rp(pemasukan_val))
            # pengeluaran per tahun (sum months for that year)
            year = ym.strftime("%Y")
            total_pengeluaran_year = 0
            for m in range(1,13):
                ym2 = f"{year}-{m:02d}"
                total_pengeluaran_year += sum(calc_month_salary(name, ym2)[0] for name in db["karyawan"].keys())
            st.metric("Total Pengeluaran (tahun)", rp(total_pengeluaran_year))

            # attendance performance: compute % hadir (hadir + hadir+lembur considered hadir) over total working days recorded
            perf_rows = []
            for name in db["karyawan"].keys():
                absen = db["karyawan"][name].get("absen", {})
                total_days = sum(1 for d in absen.keys() if d.startswith(ym_str))
                hadir_days = sum(1 for d,v in absen.items() if d.startswith(ym_str) and v.get("status") in ["hadir","hadir+lembur"])
                perf_rows.append({"nama": name.title(), "hadir": hadir_days, "recorded_days": total_days, "attendance_rate": (hadir_days/total_days*100) if total_days>0 else None})
            perf_df = pd.DataFrame(perf_rows)
            if not perf_df.empty:
                perf_df = perf_df.sort_values("attendance_rate", na_position="last", ascending=False)
                st.markdown("**Kinerja Kehadiran Karyawan (%)**")
                st.table(perf_df[["nama","hadir","recorded_days","attendance_rate"]].rename(columns={"nama":"Nama","hadir":"Hadir","recorded_days":"Hari Tercatat","attendance_rate":"% Kehadiran"}).fillna("-"))
                # chart: top 10 attendance
                chart_df = perf_df.dropna(subset=["attendance_rate"])
                if not chart_df.empty:
                    chart = alt.Chart(chart_df.reset_index()).mark_bar().encode(
                        x=alt.X("attendance_rate:Q", title="% Kehadiran"),
                        y=alt.Y("nama:N", sort='-x', title="Karyawan")
                    )
                    st.altair_chart(chart, use_container_width=True)

            # ringkasan lembur
            st.markdown("**Ringkasan Lembur (total jam per karyawan bulan ini)**")
            ot_rows = []
            for name in db["karyawan"].keys():
                absen = db["karyawan"][name].get("absen", {})
                total_ot = sum(int(v.get("overtime",0)) for d,v in absen.items() if d.startswith(ym_str))
                if total_ot>0:
                    ot_rows.append({"nama":name.title(),"total_overtime": total_ot})
            ot_df = pd.DataFrame(ot_rows)
            if not ot_df.empty:
                st.table(ot_df.sort_values("total_overtime", ascending=False).rename(columns={"nama":"Nama","total_overtime":"Jam Lembur"}))
            else:
                st.info("Belum ada data lembur untuk bulan ini.")

    # ----------------- Input Data Karyawan -----------------
    elif action == "Input Data Karyawan":
        st.subheader("➕ Input Data Karyawan")
        with st.form("input_karyawan"):
            nama = st.text_input("Nama (unique)").strip().lower()
            pw = st.text_input("Password (untuk karyawan)", type="password")
            posisi = st.selectbox("Posisi", ["intern","staff","spv","manager"])
            submitted = st.form_submit_button("Simpan")
            if submitted:
                if not nama or not pw:
                    st.warning("Nama & password harus diisi.")
                elif nama in db["karyawan"]:
                    st.error("Nama sudah ada.")
                else:
                    db["karyawan"][nama] = {"password": pw, "posisi": posisi, "absen": {}}
                    save_db(db)
                    st.success("Karyawan tersimpan.")

    # ----------------- Lihat Database -----------------
    elif action == "Lihat Database":
        st.subheader("📋 Lihat Database Karyawan")
        rows = []
        for name, info in db["karyawan"].items():
            rows.append({"Nama": name.title(), "Posisi": info.get("posisi",""), "Gaji (est.)": calc_month_salary(name, date.today().strftime("%Y-%m"))[0]})
        df = pd.DataFrame(rows)
        if df.empty:
            st.info("Database kosong.")
        else:
            df["Gaji (est.)"] = df["Gaji (est.)"].map(lambda x: f"{int(x):,}")
            st.dataframe(df, use_container_width=True)

    # ----------------- Edit Karyawan -----------------
    elif action == "Edit Karyawan":
        st.subheader("✏️ Edit Data Karyawan")
        all_names = list(db["karyawan"].keys())
        if not all_names:
            st.info("Belum ada karyawan.")
        else:
            pilih = st.selectbox("Pilih karyawan", all_names)
            info = db["karyawan"][pilih]

            new_pw = st.text_input("Password baru (opsional)", value=info["password"])
            new_pos = st.selectbox("Posisi", ["intern","staff","spv","manager"], index=["intern","staff","spv","manager"].index(info["posisi"]))

            if st.button("Simpan Perubahan"):
                db["karyawan"][pilih]["password"] = new_pw
                db["karyawan"][pilih]["posisi"] = new_pos
                save_db(db)
                st.success("Data karyawan berhasil diperbarui.")

    # ----------------- Hapus Karyawan -----------------
    elif action == "Hapus Karyawan":
        st.subheader("🗑️ Hapus Karyawan")
        names = list(db["karyawan"].keys())
        if not names:
            st.info("Tidak ada karyawan untuk dihapus.")
        else:
            pilih = st.selectbox("Pilih karyawan", names)
            if st.button("Hapus"):
                del db["karyawan"][pilih]
                save_db(db)
                st.success(f"Karyawan '{pilih}' berhasil dihapus.")

    # ----------------- Input Pemasukan Bulanan -----------------
    elif action == "Input Pemasukan Bulanan":
        st.subheader("💰 Input Pemasukan Bulanan")
        bulan = st.date_input("Pilih bulan", value=date.today())
        ym_str = bulan.strftime("%Y-%m")
        val = st.number_input("Jumlah pemasukan bulan ini", min_value=0, step=10000)
        if st.button("Simpan Pemasukan"):
            db["pemasukan"][ym_str] = int(val)
            save_db(db)
            st.success(f"Pemasukan untuk {ym_str} tersimpan.")

    # ----------------- Edit Tarif Gaji per Posisi -----------------
    elif action == "Edit Tarif Gaji per Posisi":
        st.subheader("💵 Edit Tarif Gaji")
        st.write("Tarif saat ini:", db["rates"])

        posisi = st.selectbox("Posisi", ["intern","staff","spv","manager"])
        normal = st.number_input("Tarif Normal (per jam)", min_value=0, step=5000,
                                  value=db["rates"]["normal"][posisi])
        overtime = st.number_input("Tarif Lembur (per jam)", min_value=0, step=5000,
                                   value=db["rates"]["overtime"][posisi])

        if st.button("Simpan Tarif"):
            db["rates"]["normal"][posisi] = int(normal)
            db["rates"]["overtime"][posisi] = int(overtime)
            save_db(db)
            st.success("Tarif berhasil diperbarui.")

    # ----------------- Logout Bendahara -----------------
    elif action == "Logout Bendahara":
        st.session_state.pop("bendahara", None)
        st.success("Logout berhasil.")
        st.experimental_rerun()


# ---------------------
# KARYAWAN Menu
# ---------------------
# --------------------- MENU KARYAWAN ---------------------
elif menu == "Karyawan":
    st.header("👤 Panel Karyawan")

    # Jika belum login
    if "karyawan" not in st.session_state:
        tab1, tab2 = st.tabs(["Login", "Daftar"])
        with tab1:
            karyawan_login()
        with tab2:
            karyawan_register()
        st.stop()

    # Jika sudah login
    nama = st.session_state["karyawan"]
    st.success(f"Login sebagai {nama.title()}")

    aksi = st.selectbox("Pilih Aksi", ["Absen Hari Ini", "Lihat Gaji Bulanan", "Riwayat Absensi", "Logout"])

    # ------ Absen Hari Ini ------
    if aksi == "Absen Hari Ini":
        st.subheader("📅 Absen Hari Ini")

        today = date.today().strftime("%Y-%m-%d")
        status = st.selectbox("Status", ["hadir", "hadir+lembur", "izin", "sakit", "cuti"])

        overtime = 0
        if status == "hadir+lembur":
            overtime = st.number_input("Jumlah jam lembur", min_value=1, max_value=12)

        if st.button("Simpan Absen"):
            db["karyawan"][nama]["absen"][today] = {
                "status": status,
                "overtime": overtime
            }
            save_db(db)
            st.success("Absensi tersimpan.")

    # ------ Lihat Gaji Bulanan ------
    elif aksi == "Lihat Gaji Bulanan":
        st.subheader("💵 Gaji Bulanan")
        bulan = st.date_input("Pilih bulan", value=date.today())
        ym_str = bulan.strftime("%Y-%m")

        total, rows = calc_month_salary(nama, ym_str)
        st.write(f"Total gaji bulan **{ym_str}**: {rp(total)}")

        if rows:
            df = pd.DataFrame(rows)
            df["amount"] = df["amount"].map(lambda x: f"{x:,}")
            st.dataframe(df)
        else:
            st.info("Tidak ada data absensi bulan ini.")

    # ------ Riwayat Absensi ------
    elif aksi == "Riwayat Absensi":
        st.subheader("📂 Riwayat Absensi")
        absen = db["karyawan"][nama].get("absen", {})
        if not absen:
            st.info("Belum ada data absensi.")
        else:
            rows = []
            for d, info in absen.items():
                rows.append({
                    "Tanggal": d,
                    "Status": info.get("status"),
                    "Lembur": info.get("overtime", 0)
                })
            df = pd.DataFrame(rows)
            st.dataframe(df.sort_values("Tanggal"))

    # ------ Logout ------
    elif aksi == "Logout":
        st.session_state.pop("karyawan", None)
        st.success("Logout berhasil.")
        st.experimental_rerun()

# --------------------- Keluar ---------------------
elif menu == "Keluar":
    st.write("Terima kasih telah menggunakan sistem.")


# ---------------------
# Keluar
# ---------------------
elif menu == "Keluar":
    st.write("Terima kasih — tutup tab browser untuk keluar.")
