# -*- coding: utf-8 -*-
"""sistemgaji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bd8IgNc1snHzJEV9C8Hf67yzJjmWo5nO
"""

import json
import os

# ==========================
# FILE DATABASE
# ==========================
NAMA_FILE = "databaseghe1.json"


# ==========================
# FUNGSI LOAD & SAVE DATABASE
# ==========================
def load_database():
    if not os.path.exists(NAMA_FILE):
        return {}
    with open(NAMA_FILE, "r") as f:
        return json.load(f)


def save_database(database):
    with open(NAMA_FILE, "w") as f:
        json.dump(database, f, indent=4)


# ==========================
# RATE GAJI NORMAL & LEMBUR
# ==========================
def gaji_normal(posisi):
    if posisi == "intern":
        return 50000
    elif posisi == "staff":
        return 100000
    elif posisi == "spv":
        return 150000
    elif posisi == "manager":
        return 250000
    else:
        return 0


def gaji_lembur(posisi):
    if posisi == "intern":
        return 20000
    elif posisi == "staff":
        return 35000
    elif posisi == "spv":
        return 50000
    elif posisi == "manager":
        return 100000
    else:
        return 0


# ==========================
# HITUNG GAJI PER BULAN
# ==========================
def hitung_gaji_bulanan(posisi):

    total_gaji = 0
    for minggu in range(1, 5):
        print(f"\n--- Minggu {minggu} ---")
        hari = int(input("Masuk berapa hari minggu ini? (0–7): "))

        lembur = input("Ada lembur? (y/n): ").lower()
        lembur_jam = 0
        if lembur == "y":
            lembur_jam = int(input("Berapa jam lembur minggu ini? "))

        gaji_mingguan = (hari * 8 * gaji_normal(posisi)) + (lembur_jam * gaji_lembur(posisi))
        total_gaji += gaji_mingguan

    return total_gaji


# ==========================
# LOGIN BENDAHARA
# ==========================
def login_bendahara():
    print("\n=== LOGIN BENDAHARA ===")
    email = input("Email: ")
    password = input("Password: ")

    if email == "bendahara@email.com" and password == "12345":
        print("Login berhasil!\n")
        return True
    else:
        print("Login gagal!")
        return False


# ==========================
# MENU BENDAHARA
# ==========================
def menu_bendahara(database):

    while True:
        print("\n=== MENU BENDAHARA ===")
        print("1. Input data karyawan")
        print("2. Lihat database")
        print("3. Edit data karyawan")
        print("4. Hapus data karyawan")
        print("5. Keluar")

        pilih = input("Pilih menu: ")

        # INPUT DATA BARU
        if pilih == "1":
            nama = input("Nama karyawan: ").lower()
            posisi = input("Posisi (intern/staff/spv/manager): ").lower()

            total_gaji = hitung_gaji_bulanan(posisi)

            database[nama] = {
                "posisi": posisi,
                "gaji": total_gaji
            }

            save_database(database)
            print(f"Data {nama} berhasil disimpan!")

        # LIHAT DATABASE
        elif pilih == "2":
            print("\n=== DATABASE KARYAWAN ===")
            if not database:
                print("Database kosong!")
            else:
                for nama, data in database.items():
                    print(f"Nama   : {nama}")
                    print(f"Posisi : {data['posisi']}")
                    print(f"Gaji   : Rp {data['gaji']:,}")
                    print("------------------------")

        # EDIT DATA
        elif pilih == "3":
            nama = input("Masukkan nama karyawan yang mau diedit: ").lower()

            if nama not in database:
                print("Nama tidak ditemukan!")
            else:
                print("\nApa yang mau diubah?")
                print("1. Nama")
                print("2. Hitung ulang hari masuk & lembur")
                print("3. Posisi")
                print("4. Keluar")

                sub = input("Pilih: ")

                # UBAH NAMA
                if sub == "1":
                    nama_baru = input("Nama baru: ").lower()
                    database[nama_baru] = database.pop(nama)
                    print("Nama berhasil diubah.")

                # HITUNG GAJI ULANG
                elif sub == "2":
                    posisi = database[nama]["posisi"]
                    total_gaji = hitung_gaji_bulanan(posisi)
                    database[nama]["gaji"] = total_gaji
                    print("Gaji berhasil dihitung ulang.")

                # UBAH POSISI
                elif sub == "3":
                    posisi_baru = input("Masukkan posisi baru: ").lower()
                    database[nama]["posisi"] = posisi_baru
                    print("Posisi berhasil diubah.")

                save_database(database)

        # HAPUS DATA
        elif pilih == "4":
            nama = input("Masukkan nama yang ingin dihapus: ").lower()
            if nama in database:
                del database[nama]
                save_database(database)
                print("Data berhasil dihapus.")
            else:
                print("Nama tidak ditemukan!")

        # KELUAR
        elif pilih == "5":
            break

        else:
            print("Pilihan tidak valid!")


# ==========================
# MENU KARYAWAN
# ==========================
def menu_karyawan(database):
    while True:
        print("\n=== MENU KARYAWAN ===")
        print("1. Cek gaji")
        print("2. Keluar")

        pilih = input("Pilih menu: ")

        if pilih == "1":
            nama = input("Masukkan nama Anda: ").lower()
            if nama in database:
                data = database[nama]
                print("\n=== DATA GAJI ANDA ===")
                print("Nama   :", nama)
                print("Posisi :", data["posisi"])
                print("Gaji   : Rp", format(data["gaji"], ","))
            else:
                print("Nama tidak ditemukan!")

        elif pilih == "2":
            break

        else:
            print("Pilihan tidak valid!")


# ==========================
# MENU UTAMA
# ==========================
def menu_utama():

    # Load database dari file
    database = load_database()

    while True:
        print("\n=== SISTEM GAJI KARYAWAN ===")
        print("1. Bendahara")
        print("2. Karyawan")
        print("3. Keluar")

        pilih = input("Pilih menu: ")

        if pilih == "1":
            if login_bendahara():
                menu_bendahara(database)

        elif pilih == "2":
            menu_karyawan(database)

        elif pilih == "3":
            print("Keluar...")
            break

        else:
            print("Pilihan tidak valid!")


# Jalankan program
menu_utama()